"""Verifier — validates document operations structurally and semantically.

Replaces the legacy reviewer.py.
Compares document outlines before and after execution to generate a semantic
diff, then asks Gemini to verify if all planned tasks were satisfied.
"""
from __future__ import annotations

import json
import logging
from typing import Any

from app.core.config import settings
from app.services.llm_client import LLMClient, LLMRequest

log = logging.getLogger(__name__)


class Verifier:
    """Performs structural and semantic post-execution verification."""

    def __init__(self, llm: LLMClient | None = None) -> None:
        self._llm = llm

    # ------------------------------------------------------------------
    # Stage-focused verify_semantic (Phase 5)
    # ------------------------------------------------------------------

    def verify_semantic(
        self,
        request: str,
        tasks: list[dict],
        before_outline: dict,
        after_outline: dict,
    ) -> dict:
        """Compute structural/textual diff and ask LLM if tasks were satisfied."""
        llm = self._llm or LLMClient()

        # Compute the outline diff
        diff = self._compute_outline_diff(before_outline, after_outline)

        system_prompt = (
            "You are a strict document editing verifier.\n"
            "Your job is to look at a user's original request, the list of planned tasks, "
            "and a structural/textual diff of what actually changed in the document.\n"
            "Determine if each planned task has been successfully satisfied.\n\n"
            "RULES:\n"
            "1. Be strict for structural changes. If a task says 'move section X before Y' but the order of headings in the outline "
            "shows X is still after Y, mark it as satisfied=false.\n"
            "2. Ensure you check the 'style_summary' field in the outline diff to verify formatting changes like spacing, font sizes, colors, and page breaks.\n"
            "3. If a task asks for complex aesthetic changes (like 'modernize tables' or 'make beautiful'), verify that at least some related style properties (like table_style, colors, or spacing) were updated in the diff.\n"
            "4. If all tasks are successfully satisfied, set 'all_satisfied' to true.\n"
            "5. Provide constructive feedback for any unsatisfied tasks outlining what is wrong.\n\n"
            "Return JSON matching this schema:\n"
            "{\n"
            '  "tasks": [\n'
            '    {\n'
            '      "index": 0,\n'
            '      "description": "...",\n'
            '      "satisfied": true/false,\n'
            '      "feedback": "Why it failed, or empty string"\n'
            "    }\n"
            "  ],\n"
            '  "all_satisfied": true/false\n'
            "}"
        )

        user_prompt = (
            f"Original Request: {request}\n\n"
            f"Decomposed Tasks:\n{json.dumps(tasks, indent=2)}\n\n"
            f"Outline Diff of Document Changes:\n{json.dumps(diff, indent=2)}"
        )

        response = llm.complete(LLMRequest(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0,
            max_tokens=1024,
            json_mode=True,
        ))

        parsed = response.json or {}
        
        # Parse output
        validated_tasks = []
        all_satisfied = parsed.get("all_satisfied", True)
        
        for idx, task in enumerate(tasks):
            # Find matching result
            match = next((t for t in parsed.get("tasks", []) if t.get("index") == idx), None)
            if match:
                validated_tasks.append({
                    "index": idx,
                    "description": task["description"],
                    "satisfied": bool(match.get("satisfied", False)),
                    "feedback": str(match.get("feedback", "")),
                })
                if not match.get("satisfied", False):
                    all_satisfied = False
            else:
                validated_tasks.append({
                    "index": idx,
                    "description": task["description"],
                    "satisfied": True,  # Assume satisfied if omitted
                    "feedback": "",
                })

        return {
            "all_satisfied": all_satisfied,
            "tasks": validated_tasks,
            "diff": diff,
        }

    def review_plan(self, request: str, slide_plan: dict, intent: dict) -> dict:
        """Review the initial presentation structure generated by SlidePlanner."""
        llm = self._llm or LLMClient()
        
        system_prompt = (
            "You are a presentation plan reviewer.\n"
            "Review the slide outline against the user's request.\n"
            "If the plan fulfills the core request, return {'satisfied': true}.\n"
            "If it is missing crucial topics or has severe logical flaws, return {'satisfied': false, 'feedback': 'explain the flaws'}.\n"
            "Do NOT reject purely for stylistic reasons or minor omissions. Only reject if the core intent is missed.\n"
        )
        
        user_prompt = (
            f"User request: {request}\n"
            f"Intent: {json.dumps(intent, indent=2)}\n"
            f"Generated Plan: {json.dumps(slide_plan, indent=2)}"
        )
        
        response = llm.complete(LLMRequest(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0,
            max_tokens=512,
            json_mode=True,
        ))
        
        parsed = response.json or {}
        return {
            "satisfied": parsed.get("satisfied", True),
            "feedback": parsed.get("feedback", "")
        }

    def _compute_outline_diff(self, before: dict, after: dict) -> dict:
        """Helper to compute a simplified diff of before and after outlines."""
        diff: dict[str, list] = {
            "heading_order_before": [],
            "heading_order_after": [],
            "modified_elements": [],
            "added_elements": [],
            "deleted_elements": [],
        }

        # Heading orders
        before_headings = [s.get("heading", "") for s in before.get("sections", []) if s.get("heading_id") != "start"]
        after_headings = [s.get("heading", "") for s in after.get("sections", []) if s.get("heading_id") != "start"]
        diff["heading_order_before"] = before_headings
        diff["heading_order_after"] = after_headings

        # Map elements by ID
        before_map = {}
        for s in before.get("sections", []):
            for el in s.get("elements", []):
                before_map[el["id"]] = el
        
        after_map = {}
        for s in after.get("sections", []):
            for el in s.get("elements", []):
                after_map[el["id"]] = el

        # Detect additions and modifications
        for el_id, after_el in after_map.items():
            if el_id not in before_map:
                diff["added_elements"].append({
                    "id": el_id,
                    "type": after_el.get("type"),
                    "preview": after_el.get("text_preview", ""),
                })
            else:
                before_el = before_map[el_id]
                # Compare text preview or other values
                changed = []
                if before_el.get("text_preview") != after_el.get("text_preview"):
                    changed.append("text")
                if before_el.get("rows") != after_el.get("rows") or before_el.get("cols") != after_el.get("cols"):
                    changed.append("table_dimensions")
                if before_el.get("size") != after_el.get("size"):
                    changed.append("image_size")
                if before_el.get("style_summary") != after_el.get("style_summary"):
                    changed.append("style")
                if before_el.get("alignment") != after_el.get("alignment"):
                    changed.append("alignment")
                
                if changed:
                    diff_entry = {
                        "id": el_id,
                        "type": after_el.get("type"),
                        "changes": changed,
                        "before_preview": before_el.get("text_preview", ""),
                        "after_preview": after_el.get("text_preview", ""),
                    }
                    if "style" in changed:
                        diff_entry["before_style"] = before_el.get("style_summary", [])
                        diff_entry["after_style"] = after_el.get("style_summary", [])
                    if "alignment" in changed:
                        diff_entry["before_alignment"] = before_el.get("alignment")
                        diff_entry["after_alignment"] = after_el.get("alignment")
                        
                    diff["modified_elements"].append(diff_entry)

        # Detect deletions
        for el_id, before_el in before_map.items():
            if el_id not in after_map:
                diff["deleted_elements"].append({
                    "id": el_id,
                    "type": before_el.get("type"),
                    "preview": before_el.get("text_preview", ""),
                })

        return diff
